import './globals.scss'
import { Inter } from 'next/font/google'
import Header from "@/Components/Header";
import Footer from "@/Components/Footer";
import Image from "next/image";
import {notFound} from "next/navigation";
import {NextIntlClientProvider, useLocale} from "next-intl";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'SAFE LIFE',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, params
}: {
  children: React.ReactNode,
  params:any
,}) {

  const locale = useLocale();


  if (params.locale !== locale) {
    notFound();
  }


  return <>
    <head lang={locale}>
      <meta charSet="utf-8"/>
        <base href=""/>
      <meta charSet="utf-8"/>
      <meta name="viewport" content="width=device-width, initial-scale=1"/>
      <meta name="authors" content="Taleh Maharramov, Elgiz Ismayilov"/>
      <meta
          name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1.0, shrink-to-fit=no"
      />
      <meta property="og:site_name" content="SAFE LIFE" />
      <meta property="og:locale" content="az_AZE" />
        <link href="/SL.png" rel="shortcut icon" type="image/x-icon"/>
        <link rel="stylesheet" href="https://arsenalfire.az/cache/widgetkit/widgetkit-7d587801.css" type="text/css"/>
        <script defer type="text/javascript" src="https://arsenalfire.az/media/system/js/mootools.js"></script>
        <script defer type="text/javascript" src="https://arsenalfire.az/media/system/js/caption.js"></script>
        <script defer type="text/javascript" src="https://arsenalfire.az/media/widgetkit/js/jquery.js"></script>
        <script defer type="text/javascript" src="https://arsenalfire.az/cache/widgetkit/widgetkit-8deed6f1.js"></script>
        <script defer type="text/javascript" src="https://arsenalfire.az/templates/safelife/warp/js/search.js"></script>
        <script defer type="text/javascript" src="https://arsenalfire.az/modules/mod_imgscrawler/tmpl/crawler.js"></script>

        <link rel="apple-touch-icon-precomposed"
              href="https://arsenalfire.az/templates/safelife/apple_touch_icon.png"/>
        <link rel="stylesheet" href="https://arsenalfire.az/templates/safelife/css/base.css"/>
        <link rel="stylesheet" href="https://arsenalfire.az/templates/safelife/css/layout.css"/>
        <link rel="stylesheet" href="https://arsenalfire.az/templates/safelife/css/menus.css"/>
        <link rel="stylesheet" href="https://arsenalfire.az/templates/safelife/css/modules.css"/>
        <link rel="stylesheet" href="https://arsenalfire.az/templates/safelife/css/tools.css"/>
        <link rel="stylesheet" href="https://arsenalfire.az/templates/safelife/styles/light/css/system.css"/>
        <link rel="stylesheet" href="https://arsenalfire.az/templates/safelife/styles/light/css/extensions.css"/>
        <link rel="stylesheet" href="https://arsenalfire.az/templates/safelife/css/custom.css"/>
        <link rel="stylesheet" href="https://arsenalfire.az/templates/safelife/styles/light/css/color/red.css"/>
        <link rel="stylesheet" href="https://arsenalfire.az/templates/safelife/css/font2/metrophobic.css"/>
        <link rel="stylesheet" href="https://arsenalfire.az/templates/safelife/css/font3/ubuntu.css"/>
        <link rel="stylesheet" href="https://arsenalfire.az/templates/safelife/styles/light/css/style.css"/>
        <link rel="stylesheet" href="https://arsenalfire.az/templates/safelife/css/print.css"/>
        <link rel="stylesheet" href="https://arsenalfire.az/templates/safelife/fonts/metrophobic.css"/>
        <link rel="stylesheet" href="https://arsenalfire.az/templates/safelife/fonts/ubuntu.css"/>
        <script defer src="https://arsenalfire.az/templates/safelife/warp/js/warp.js"></script>
        <script defer src="https://arsenalfire.az/templates/safelife/warp/js/accordionmenu.js"></script>
        <script defer src="https://arsenalfire.az/templates/safelife/warp/js/dropdownmenu.js"></script>
        <script defer src="https://arsenalfire.az/templates/safelife/js/template.js"></script>
    </head>
    <html lang="en">
    <body className={'page sidebar-a-right sidebar-b-right isblog hassearch '}>
    <Header/>
    <NextIntlClientProvider locale={locale} >
      {children}
    </NextIntlClientProvider>

    <Footer/>
    </body>
    </html>
  </>
}
